version: '3.8'
services:
  ## Nginx
  nginx:
    build:
      context: ./nginx
    image: nginx-vp-app
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    networks:
      - vp-app-network
    depends_on:
      - app01

  ## Application
  app01:
    build:
      context: ./tom-app
    image: tomcat-vp-app
    container_name: app01
    ports:
      - "8080:8080"
    networks:
      - vp-app-network
    depends_on:
      - db01
      - mc01
      - rmq01

  ## Database
  db01:
    build:
      context: ./db
    image: mysql-vp-app
    container_name: db01
    ports:
      - "3306:3306"
    networks:
      - vp-app-network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=admin
      - MYSQL_DATABASE=accounts

  ## Memcached
  mc01:
    image: memcached
    container_name: mc01
    ports:
      - "11211:11211"
    networks:
      - vp-app-network

  ## RabbitMQ
  rmq01:
    image: rabbitmq
    container_name: rmq01
    ports:
      - "5672:5672"
    networks:
      - vp-app-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  vp-app-network:
    driver: bridge

volumes:
  db_data:
